# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  variables:
    sql_mode: TRADITIONAL

development:
  adapter: mysql2
  database: demo
  username: root
  password: ""
  host: localhost
  variables:
    sql_mode: TRADITIONAL

test:
  adapter: mysql2
  database: demo
  username: root
  password: ""
  host: localhost
  variables:
    sql_mode: TRADITIONAL

production:
  adapter: mysql2
  database: demo
  username: root
  password: ""
  host: localhost
  variables:
    sql_mode: TRADITIONAL